Shader "Hidden/ContrastComposite" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "" {}
		_MainTexBlurred ("Base Blurred (RGB)", 2D) = "" {}
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 20952
			Program "vp" {
				SubProgram "d3d9 " {
					"!!vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_TexelSize;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_TexelSize  c8       1
					//
					
					    vs_3_0
					    def c9, 1, 0, -2, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    dcl_texcoord1 o2.xy
					    mad r0, v0.xyzx, c9.xxxy, c9.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov r0.y, c9.y
					    slt r0.x, c8.y, r0.y
					    mad r0.y, v1.y, c9.z, c9.x
					    mad o1.y, r0.x, r0.y, v1.y
					    mov o1.x, v1.x
					    mov o2.xy, v1
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 17 instruction slots used"
				}
				SubProgram "d3d11 " {
					"!!vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					layout(std140) uniform VGlobals {
						vec4 unused_0_0[2];
						vec4 _MainTex_TexelSize;
						vec4 unused_0_2;
					};
					layout(std140) uniform UnityPerDraw {
						mat4x4 unity_ObjectToWorld;
						vec4 unused_1_1[6];
					};
					layout(std140) uniform UnityPerFrame {
						vec4 unused_2_0[17];
						mat4x4 unity_MatrixVP;
						vec4 unused_2_2[3];
					};
					in  vec4 in_POSITION0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec2 vs_TEXCOORD1;
					vec4 u_xlat0;
					bool u_xlatb0;
					vec4 u_xlat1;
					float u_xlat2;
					void main()
					{
					    u_xlat0 = in_POSITION0.yyyy * unity_ObjectToWorld[1];
					    u_xlat0 = unity_ObjectToWorld[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = unity_ObjectToWorld[2] * in_POSITION0.zzzz + u_xlat0;
					    u_xlat0 = u_xlat0 + unity_ObjectToWorld[3];
					    u_xlat1 = u_xlat0.yyyy * unity_MatrixVP[1];
					    u_xlat1 = unity_MatrixVP[0] * u_xlat0.xxxx + u_xlat1;
					    u_xlat1 = unity_MatrixVP[2] * u_xlat0.zzzz + u_xlat1;
					    gl_Position = unity_MatrixVP[3] * u_xlat0.wwww + u_xlat1;
					    u_xlatb0 = _MainTex_TexelSize.y<0.0;
					    u_xlat2 = (-in_TEXCOORD0.y) + 1.0;
					    vs_TEXCOORD0.y = (u_xlatb0) ? u_xlat2 : in_TEXCOORD0.y;
					    vs_TEXCOORD0.x = in_TEXCOORD0.x;
					    vs_TEXCOORD1.xy = in_TEXCOORD0.xy;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"!!ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   sampler2D _MainTexBlurred;
					//   float intensity;
					//   float threshold;
					//
					//
					// Registers:
					//
					//   Name            Reg   Size
					//   --------------- ----- ----
					//   intensity       c0       1
					//   threshold       c1       1
					//   _MainTex        s0       1
					//   _MainTexBlurred s1       1
					//
					
					    ps_3_0
					    def c2, 0, 1, -0, -1
					    dcl_texcoord v0.xy
					    dcl_texcoord1 v1.xy
					    dcl_2d s0
					    dcl_2d s1
					    texld_pp r0, v0, s1
					    texld_pp r1, v1, s0
					    add_pp r0, -r0, r1
					    cmp_pp r2, -r0, c2.x, c2.y
					    cmp_pp r3, r0, c2.z, c2.w
					    add_sat r0, r0_abs, -c1.x
					    add_pp r2, r2, r3
					    mul r0, r0, r2
					    mov r2.y, c2.y
					    add r2.x, r2.y, -c1.x
					    rcp r2.x, r2.x
					    mul_pp r0, r0, r2.x
					    mad_pp oC0, r0, c0.x, r1
					
					// approximately 13 instruction slots used (2 texture, 11 arithmetic)"
				}
				SubProgram "d3d11 " {
					"!!ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					layout(std140) uniform PGlobals {
						vec4 unused_0_0[3];
						float intensity;
						float threshold;
					};
					uniform  sampler2D _MainTex;
					uniform  sampler2D _MainTexBlurred;
					in  vec2 vs_TEXCOORD0;
					in  vec2 vs_TEXCOORD1;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat10_0;
					vec4 u_xlat10_1;
					vec4 u_xlat2;
					ivec4 u_xlati2;
					ivec4 u_xlati3;
					void main()
					{
					    u_xlat10_0 = texture(_MainTexBlurred, vs_TEXCOORD0.xy);
					    u_xlat10_1 = texture(_MainTex, vs_TEXCOORD1.xy);
					    u_xlat0 = (-u_xlat10_0) + u_xlat10_1;
					    u_xlati2 = ivec4(uvec4(lessThan(vec4(0.0, 0.0, 0.0, 0.0), u_xlat0)) * 0xFFFFFFFFu);
					    u_xlati3 = ivec4(uvec4(lessThan(u_xlat0, vec4(0.0, 0.0, 0.0, 0.0))) * 0xFFFFFFFFu);
					    u_xlat0 = abs(u_xlat0) + (-vec4(vec4(threshold, threshold, threshold, threshold)));
					    u_xlat0 = clamp(u_xlat0, 0.0, 1.0);
					    u_xlati2 = (-u_xlati2) + u_xlati3;
					    u_xlat2 = vec4(u_xlati2);
					    u_xlat0 = u_xlat0 * u_xlat2;
					    u_xlat2.x = (-threshold) + 1.0;
					    u_xlat0 = u_xlat0 / u_xlat2.xxxx;
					    SV_Target0 = u_xlat0 * vec4(intensity) + u_xlat10_1;
					    return;
					}"
				}
			}
		}
	}
}