Shader "Hidden/ProBuilder/HideVertices" {
	Properties {
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "RenderType" = "Geometry" }
		Pass {
			Tags { "IGNOREPROJECTOR" = "true" "RenderType" = "Geometry" }
			ZClip Off
			GpuProgramID 20957
			Program "vp" {
				SubProgram "d3d9 " {
					"!!vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					    vs_3_0
					    def c0, 0, 0, 0, 0
					    dcl_position o0
					    mov r0, c0.x
					    mad o0.xy, r0.w, c255, r0
					    mov o0.zw, r0
					
					// approximately 3 instruction slots used"
				}
				SubProgram "d3d11 " {
					"!!vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					void main()
					{
					    gl_Position = vec4(0.0, 0.0, 0.0, 0.0);
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"!!ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					    ps_3_0
					    def c0, 0, 0, 0, 0
					    mov_pp oC0, c0.x
					
					// approximately 1 instruction slot used"
				}
				SubProgram "d3d11 " {
					"!!ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					layout(location = 0) out vec4 SV_Target0;
					void main()
					{
					    SV_Target0 = vec4(0.0, 0.0, 0.0, 0.0);
					    return;
					}"
				}
			}
		}
	}
}